openapi: 3.0.0
info:
  title: 'API Documentation'
  contact:
    email: info@mail.com
  version: '0.1'
servers:
  -
    url: 'https://localhost/api/'
    description: Server
paths:
  /auto:
    get:
      tags:
        - Auto
      operationId: 245ac8a371c45c1c483c49c96116fd5f
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AutoResource'
        '401':
          description: Unauthorized
        '404':
          description: 'Not Found'
    post:
      tags:
        - Auto
      operationId: cae1ab0d913d32c1e71066d832dc1af9
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AutoRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AutoResource'
        '401':
          description: Unauthorized
        '404':
          description: 'Not Found'
  '/auto/{id}':
    delete:
      tags:
        - Auto
      operationId: 1dc1c9060f0e18e3dee7db082bd526f8
      parameters:
        -
          name: id
          in: path
          description: 'ID of auto'
          required: true
          schema:
            type: integer
      responses:
        '201':
          description: Ok
        '401':
          description: Unauthorized
        '404':
          description: 'Not Found'
    patch:
      tags:
        - Auto
      operationId: beea1edf8a9fdfb7d9547189da17ebdb
      parameters:
        -
          name: id
          in: path
          description: 'ID of auto'
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AutoRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AutoResource'
        '401':
          description: Unauthorized
        '404':
          description: 'Not Found'
  /auto_mark:
    get:
      tags:
        - Auto
      operationId: a3ecdf9e756384de939ade4aaf2b87d7
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AutoMarkResource'
        '401':
          description: Unauthorized
        '404':
          description: 'Not Found'
    post:
      tags:
        - Auto
      operationId: f97e01c91502559c0916735cb4865325
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AutoMarkRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AutoMarkResource'
        '401':
          description: Unauthorized
        '404':
          description: 'Not Found'
  '/auto_mark/{id}':
    delete:
      tags:
        - Auto
      operationId: d453fd4b9ec596e886186dd189ca8247
      parameters:
        -
          name: id
          in: path
          description: 'ID of auto mark'
          required: true
          schema:
            type: integer
      responses:
        '201':
          description: Ok
        '401':
          description: Unauthorized
        '404':
          description: 'Not Found'
    patch:
      tags:
        - Auto
      operationId: 84f63c3323a5305e2404d3ff95072f24
      parameters:
        -
          name: id
          in: path
          description: 'ID of auto mark'
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AutoMarkRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AutoMarkResource'
        '401':
          description: Unauthorized
        '404':
          description: 'Not Found'
  /auto_model:
    get:
      tags:
        - Auto
      operationId: 01fd57b871819e3a209e3c4e2646b43e
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AutoModelResource'
        '401':
          description: Unauthorized
        '404':
          description: 'Not Found'
    post:
      tags:
        - Auto
      operationId: 9be62fbbb2a9864655140374905b1281
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AutoModelRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AutoModelResource'
        '401':
          description: Unauthorized
        '404':
          description: 'Not Found'
  '/auto_model/{id}':
    delete:
      tags:
        - Auto
      operationId: 9bc0f999e51d1b11aab75135697cb1f3
      parameters:
        -
          name: id
          in: path
          description: 'ID of auto model'
          required: true
          schema:
            type: integer
      responses:
        '201':
          description: Ok
        '401':
          description: Unauthorized
        '404':
          description: 'Not Found'
    patch:
      tags:
        - Auto
      operationId: c6be81a9458127495efe0c6db8b3c7e3
      parameters:
        -
          name: id
          in: path
          description: 'ID of auto model'
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AutoModelRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AutoModelResource'
        '401':
          description: Unauthorized
        '404':
          description: 'Not Found'
  /auth/login:
    post:
      tags:
        - Authorization
      operationId: 6ac96e5dfa799cab4041324fc232ac42
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLoginRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: {  }
        '401':
          description: UNAUTHORIZED
components:
  schemas:
    AutoMarkRequest:
      required:
        - name
      properties:
        name:
          $ref: '#/components/schemas/AutoMark/properties/name'
      type: object
    AutoModelRequest:
      required:
        - name
      properties:
        name:
          $ref: '#/components/schemas/AutoModel/properties/name'
      type: object
    AutoRequest:
      required:
        - year
        - mileage
        - color
        - model_id
        - mark_id
      properties:
        year:
          $ref: '#/components/schemas/Auto/properties/year'
        mileage:
          $ref: '#/components/schemas/Auto/properties/mileage'
        color:
          $ref: '#/components/schemas/Auto/properties/color'
        model_id:
          $ref: '#/components/schemas/Auto/properties/auto_model_id'
        mark_id:
          $ref: '#/components/schemas/Auto/properties/auto_mark_id'
        user_id:
          $ref: '#/components/schemas/Auto/properties/user_id'
      type: object
    Auto:
      properties:
        id:
          description: ID
          type: integer
          example: '1'
        year:
          description: Year
          type: integer
          example: '2025'
        mileage:
          description: Mileage
          type: integer
          example: '10000'
        color:
          description: Color
          type: string
          example: Black
        auto_model_id:
          description: 'Model ID'
          type: integer
          example: '1'
        auto_mark_id:
          description: 'Mark ID'
          type: integer
          example: '1'
        user_id:
          description: 'User ID'
          type: integer
          example: '1'
          nullable: true
        mark:
          $ref: '#/components/schemas/AutoMark'
        model:
          $ref: '#/components/schemas/AutoModel'
        created_at:
          description: 'Created at'
          type: string
          format: date-time
          example: '2025-01-01 00:00:01'
        updated_at:
          description: 'Updated at'
          type: string
          format: date-time
          example: '2025-01-01 00:00:01'
      type: object
    AutoMark:
      properties:
        id:
          description: ID
          type: integer
          example: '1'
        name:
          description: 'AutoMark name'
          type: string
          example: BMW
        created_at:
          description: 'Created at'
          type: string
          format: date-time
          example: '2025-01-01 00:00:01'
        updated_at:
          description: 'Updated at'
          type: string
          format: date-time
          example: '2025-01-01 00:00:01'
      type: object
    AutoModel:
      properties:
        id:
          description: ID
          type: integer
          example: '1'
        name:
          description: 'AutoModel name'
          type: string
          example: M6
        created_at:
          description: 'Created at'
          type: string
          format: date-time
          example: '2025-01-01 00:00:01'
        updated_at:
          description: 'Updated at'
          type: string
          format: date-time
          example: '2025-01-01 00:00:01'
      type: object
    AutoMarkResource:
      properties:
        id:
          $ref: '#/components/schemas/AutoMark/properties/id'
        name:
          $ref: '#/components/schemas/AutoMark/properties/name'
        created_at:
          $ref: '#/components/schemas/AutoMark/properties/created_at'
        updated_at:
          $ref: '#/components/schemas/AutoMark/properties/updated_at'
      type: object
    AutoModelResource:
      properties:
        id:
          $ref: '#/components/schemas/AutoModel/properties/id'
        name:
          $ref: '#/components/schemas/AutoModel/properties/name'
        created_at:
          $ref: '#/components/schemas/AutoModel/properties/created_at'
        updated_at:
          $ref: '#/components/schemas/AutoModel/properties/updated_at'
      type: object
    AutoResource:
      properties:
        data:
          properties:
            id:
              $ref: '#/components/schemas/Auto/properties/id'
            year:
              $ref: '#/components/schemas/Auto/properties/year'
            mileage:
              $ref: '#/components/schemas/Auto/properties/mileage'
            color:
              $ref: '#/components/schemas/Auto/properties/color'
            model:
              $ref: '#/components/schemas/AutoModel'
            mark:
              $ref: '#/components/schemas/AutoMark'
            created_at:
              $ref: '#/components/schemas/Auto/properties/created_at'
            updated_at:
              $ref: '#/components/schemas/Auto/properties/updated_at'
          type: object
      type: object
    UserLoginRequest:
      required:
        - email
        - password
      properties:
        email:
          description: E-Mail
          type: string
          example: test@test.com
        password:
          description: 'User password'
          type: string
          example: '123456'
      type: object
    User:
      properties:
        id:
          description: ID
          type: integer
          example: '1'
        name:
          description: Name
          type: integer
          example: 'User name'
        email:
          description: E-Mail
          type: integer
          example: mail@mail.com
        created_at:
          description: 'Created at'
          type: string
          format: date-time
          example: '2025-01-01 00:00:01'
        updated_at:
          description: 'Updated at'
          type: string
          format: date-time
          example: '2025-01-01 00:00:01'
      type: object
    UserLoginResource:
      properties:
        token:
          description: 'Access token'
          type: string
          example: 123-456-789
      type: object
tags:
  -
    name: Auto
    description: Auto
  -
    name: Authorization
    description: Authorization
